FROM arm32v7/node:alpine
WORKDIR /app/
COPY package*.json ./
RUN apk add --no-cache
RUN apk add python make gcc g++
RUN npm install node-opcua
RUN npm install --production
COPY app.js ./
USER node
CMD ["node", "app.js"]
